steps:
  - label: "Staging"
    trigger: "image-gallery-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        AWS_REGION: "us-east-1"
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_ACCOUNT_ID: "027610500199"
        ROLE_ARN: arn:aws:iam::027610500199:role/buildkite
        STAGE: "staging"
  - label: "Production"
    trigger: "image-gallery-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        AWS_REGION: "us-east-1"
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_ACCOUNT_ID: "027610500199"
        ROLE_ARN: arn:aws:iam::027610500199:role/buildkite
        STAGE: "production"